import{i as w,A as E,a as q,S as B}from"./assets/vendor-Cv84vpVH.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function l(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=l(t);fetch(t.href,o)}})();const M=document.querySelector(".js-open-menu"),h=document.querySelector("#close-modal"),g=document.querySelector(".js-modal"),y=document.querySelector(".modal-nav-item");function x(){g.classList.remove("is-hidden"),h.addEventListener("click",a),y.addEventListener("click",a)}function a(){g.classList.add("is-hidden"),h.removeEventListener("click",a),y.removeEventListener("click",a)}M.addEventListener("click",x);const n=document.querySelectorAll(".project-item"),u=document.querySelector(".btn-load");let s=0;const b=()=>{for(let r=s;r<s+3;r++)n[r]&&(n[r].classList.remove("is-hidden"),u.classList.remove("is-hidden"));const e=n[0].getBoundingClientRect().height;window.scrollBy({top:e*.5,left:0,behavior:"smooth"}),s+=3,s>=n.length&&(u.classList.add("is-hidden"),w.info({message:"Sorry, this is the last project",position:"topRight"}))};u.addEventListener("click",b);b();new E(".accordion-container",{elementClass:"ac-item",triggerClass:"ac-header",panelClass:"ac-panel",duration:4e3,openOnInit:[0],beforeOpen:e=>e.querySelector("button.ac-trigger").setAttribute("aria-expanded",!0),beforeClose:e=>e.querySelector("button.ac-trigger").setAttribute("aria-expanded",!1)});const k="https://portfolio-js.b.goit.study/api/reviews",L=document.querySelector(".reviews-list"),p=document.querySelector(".swiper-next-btn"),f=document.querySelector(".swiper-prev-btn"),O=document.querySelector(".reviews");let c=!1;async function A(){try{const r=(await q.get(k)).data;r.length===0?c=!1:(c=!0,I(r),j())}catch(e){c=!1,console.error(e)}}function I(e){const r=e.map(({author:l,avatar_url:i,review:t})=>`
        <li class="swiper-slide review-item">
          <div class="review-item-container">
            <p class="review-text">${t}</p>
            <div class="author-info">
              <img class="author-avatar" src="${i}" alt="Author avatar" />
              <p class="author-name">${l}</p>
            </div>
          </div>
        </li>
      `).join("");L.innerHTML=r}function j(){new B(".swiper",{slidesPerView:1,spaceBetween:10,navigation:{nextEl:".swiper-prev-btn",prevEl:".swiper-next-btn"},keyboard:{enabled:!0,onlyInViewport:!0},breakpoints:{1280:{slidesPerView:2,spaceBetween:32}},on:{reachEnd(){p.disabled=!0},reachBeginning(){f.disabled=!0},fromEdge(){p.disabled=!1,f.disabled=!1}}})}const S=new IntersectionObserver(e=>{e.forEach(r=>{r.isIntersecting&&!c&&(N(),S.unobserve(r.target))})});S.observe(O);function N(){w.error({title:"Error",message:"Reviews not found.",position:"topRight"}),L.innerHTML=`
    <li class="swiper-slide review-item">
      <div class="review-item-container">
        <p class="review-text">Not Found</p>
      </div>
    </li>
  `,f.disabled=!0,p.disabled=!0}A();const m=document.querySelector(".backdrop"),P=document.querySelector(".modal-close-btn");function v(){m.style.display="none"}P.addEventListener("click",v);document.addEventListener("keydown",function(e){e.key==="Escape"&&v()});m.addEventListener("click",function(e){e.target===m&&v()});
//# sourceMappingURL=index.js.map
